[package]
authors = ["Mrmaxmeier <Mrmaxmeier@gmail.com>"]
name = "server"
version = "0.1.0"

[dependencies]
nickel = "^0.8.0"
plugin = "^0.2.6"
r2d2 = "^0.7.0"
r2d2_redis = "0.4.0"
redis = "^0.6.0"
rustc-serialize = "^0.3.19"
typemap = "^0.3.3"
